export { default as Home } from './Home'
export { default as Read } from './Read'
export { default as Update } from './Update'
export { default as Delete } from './Delete'
export { default as User } from './User'